//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace Vocada.Veriphy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "VeriphyNotifierSoap", Namespace = "http://tempuri.org/")]
    public partial class NotifierServiceProxy : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        /// <remarks/>
        public NotifierServiceProxy(string url)
        {
            //this.Url = "http://xipl63/VeriphyNotifierDev/VeriphyNotifier.asmx";
            this.Url = url;
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EscalateMessages", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EscalateMessages()
        {
            object[] results = this.Invoke("EscalateMessages", new object[0]);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEscalateMessages(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EscalateMessages", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public int EndEscalateMessages(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewMessage", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NewMessage(int messageID)
        {
            object[] results = this.Invoke("NewMessage", new object[] {
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginNewMessage(int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("NewMessage", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndNewMessage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewReply", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NewReply(int messageReplyID)
        {
            object[] results = this.Invoke("NewReply", new object[] {
                    messageReplyID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginNewReply(int messageReplyID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("NewReply", new object[] {
                    messageReplyID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndNewReply(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessageRead", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MessageRead(int messageID)
        {
            object[] results = this.Invoke("MessageRead", new object[] {
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginMessageRead(int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("MessageRead", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndMessageRead(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResendMessageNotification", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ResendMessageNotification(int messageID, int notificationID)
        {
            object[] results = this.Invoke("ResendMessageNotification", new object[] {
                    messageID,
                    notificationID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginResendMessageNotification(int messageID, int notificationID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ResendMessageNotification", new object[] {
                    messageID,
                    notificationID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndResendMessageNotification(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessageDeclined", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MessageDeclined(int messageID)
        {
            object[] results = this.Invoke("MessageDeclined", new object[] {
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginMessageDeclined(int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("MessageDeclined", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndMessageDeclined(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessageReadback", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MessageReadback(int readbackID, int messageID)
        {
            object[] results = this.Invoke("MessageReadback", new object[] {
                    readbackID,
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginMessageReadback(int readbackID, int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("MessageReadback", new object[] {
                    readbackID,
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndMessageReadback(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessageReadbackAccepted", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MessageReadbackAccepted(int readbackID, int messageID, bool accepted)
        {
            object[] results = this.Invoke("MessageReadbackAccepted", new object[] {
                    readbackID,
                    messageID,
                    accepted});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginMessageReadbackAccepted(int readbackID, int messageID, bool accepted, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("MessageReadbackAccepted", new object[] {
                    readbackID,
                    messageID,
                    accepted}, callback, asyncState);
        }

        /// <remarks/>
        public int EndMessageReadbackAccepted(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewLabMessage", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NewLabMessage(int labMessageID)
        {
            object[] results = this.Invoke("NewLabMessage", new object[] {
                    labMessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginNewLabMessage(int labMessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("NewLabMessage", new object[] {
                    labMessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndNewLabMessage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResendLabMessageNotification", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ResendLabMessageNotification(int labMessageID, int notificationID)
        {
            object[] results = this.Invoke("ResendLabMessageNotification", new object[] {
                    labMessageID,
                    notificationID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginResendLabMessageNotification(int labMessageID, int notificationID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ResendLabMessageNotification", new object[] {
                    labMessageID,
                    notificationID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndResendLabMessageNotification(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LabMessageRead", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LabMessageRead(int labMessageID)
        {
            object[] results = this.Invoke("LabMessageRead", new object[] {
                    labMessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLabMessageRead(int labMessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("LabMessageRead", new object[] {
                    labMessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndLabMessageRead(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LabMessageDeclined", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LabMessageDeclined(int labMessageID)
        {
            object[] results = this.Invoke("LabMessageDeclined", new object[] {
                    labMessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLabMessageDeclined(int labMessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("LabMessageDeclined", new object[] {
                    labMessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndLabMessageDeclined(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LabMessageReadback", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LabMessageReadback(int labMessageID)
        {
            object[] results = this.Invoke("LabMessageReadback", new object[] {
                    labMessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLabMessageReadback(int labMessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("LabMessageReadback", new object[] {
                    labMessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndLabMessageReadback(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewLabMessageReply", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NewLabMessageReply(int labReplyMessageID, int labMessageID)
        {
            object[] results = this.Invoke("NewLabMessageReply", new object[] {
                    labReplyMessageID,
                    labMessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginNewLabMessageReply(int labReplyMessageID, int labMessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("NewLabMessageReply", new object[] {
                    labReplyMessageID,
                    labMessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndNewLabMessageReply(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LabMessageReadbackFailure", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LabMessageReadbackFailure(int labMessageID)
        {
            object[] results = this.Invoke("LabMessageReadbackFailure", new object[] {
                    labMessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginLabMessageReadbackFailure(int labMessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("LabMessageReadbackFailure", new object[] {
                    labMessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndLabMessageReadbackFailure(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TEST_OutboundCall", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TEST_OutboundCall(string phoneNumber)
        {
            object[] results = this.Invoke("TEST_OutboundCall", new object[] {
                    phoneNumber});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTEST_OutboundCall(string phoneNumber, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("TEST_OutboundCall", new object[] {
                    phoneNumber}, callback, asyncState);
        }

        /// <remarks/>
        public string EndTEST_OutboundCall(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TEST_GetCallStatus", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TEST_GetCallStatus(string sessionID)
        {
            object[] results = this.Invoke("TEST_GetCallStatus", new object[] {
                    sessionID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTEST_GetCallStatus(string sessionID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("TEST_GetCallStatus", new object[] {
                    sessionID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndTEST_GetCallStatus(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewDepartmentMessage", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NewDepartmentMessage(int messageID)
        {
            object[] results = this.Invoke("NewDepartmentMessage", new object[] {
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginNewDepartmentMessage(int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("NewDepartmentMessage", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndNewDepartmentMessage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DepartmentMessageDeclined", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DepartmentMessageDeclined(int messageID)
        {
            object[] results = this.Invoke("DepartmentMessageDeclined", new object[] {
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDepartmentMessageDeclined(int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DepartmentMessageDeclined", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndDepartmentMessageDeclined(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DepartmentMessageRead", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DepartmentMessageRead(int messageID)
        {
            object[] results = this.Invoke("DepartmentMessageRead", new object[] {
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDepartmentMessageRead(int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DepartmentMessageRead", new object[] {
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndDepartmentMessageRead(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DepartmentMessageReadback", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DepartmentMessageReadback(int readbackID, int messageID)
        {
            object[] results = this.Invoke("DepartmentMessageReadback", new object[] {
                    readbackID,
                    messageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDepartmentMessageReadback(int readbackID, int messageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DepartmentMessageReadback", new object[] {
                    readbackID,
                    messageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndDepartmentMessageReadback(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DepartmentMessageReadbackAccepted", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DepartmentMessageReadbackAccepted(int readbackID, int messageID, bool accepted)
        {
            object[] results = this.Invoke("DepartmentMessageReadbackAccepted", new object[] {
                    readbackID,
                    messageID,
                    accepted});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDepartmentMessageReadbackAccepted(int readbackID, int messageID, bool accepted, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DepartmentMessageReadbackAccepted", new object[] {
                    readbackID,
                    messageID,
                    accepted}, callback, asyncState);
        }

        /// <remarks/>
        public int EndDepartmentMessageReadbackAccepted(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewDepartmentReply", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NewDepartmentReply(int MessageReplyID, int MessageID)
        {
            object[] results = this.Invoke("NewDepartmentReply", new object[] {
                    MessageReplyID,
                    MessageID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginNewDepartmentReply(int MessageReplyID, int MessageID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("NewDepartmentReply", new object[] {
                    MessageReplyID,
                    MessageID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndNewDepartmentReply(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResendDepartmentMessageNotification", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ResendDepartmentMessageNotification(int messageID, int notificationID)
        {
            object[] results = this.Invoke("ResendDepartmentMessageNotification", new object[] {
                    messageID,
                    notificationID});
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginResendDepartmentMessageNotification(int messageID, int notificationID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ResendDepartmentMessageNotification", new object[] {
                    messageID,
                    notificationID}, callback, asyncState);
        }

        /// <remarks/>
        public int EndResendDepartmentMessageNotification(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResendAllNotifications", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ResendAllNotifications(int messageID, int[] notificationList, bool isLabMessage, bool isDepartmentMessage, out string errorMessage)
        {
            object[] results = this.Invoke("ResendAllNotifications", new object[] {
                    messageID,
                    notificationList,
                    isLabMessage,
                    isDepartmentMessage});
            errorMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginResendAllNotifications(int messageID, int[] notificationList, bool isLabMessage, bool isDepartmentMessage, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ResendAllNotifications", new object[] {
                    messageID,
                    notificationList,
                    isLabMessage,
                    isDepartmentMessage}, callback, asyncState);
        }

        /// <remarks/>
        public int EndResendAllNotifications(System.IAsyncResult asyncResult, out string errorMessage)
        {
            object[] results = this.EndInvoke(asyncResult);
            errorMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void EscalateMessagesCompletedEventHandler(object sender, EscalateMessagesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EscalateMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EscalateMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void NewMessageCompletedEventHandler(object sender, NewMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal NewMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void NewReplyCompletedEventHandler(object sender, NewReplyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewReplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal NewReplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void MessageReadCompletedEventHandler(object sender, MessageReadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal MessageReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ResendMessageNotificationCompletedEventHandler(object sender, ResendMessageNotificationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResendMessageNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ResendMessageNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void MessageDeclinedCompletedEventHandler(object sender, MessageDeclinedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageDeclinedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal MessageDeclinedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void MessageReadbackCompletedEventHandler(object sender, MessageReadbackCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageReadbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal MessageReadbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void MessageReadbackAcceptedCompletedEventHandler(object sender, MessageReadbackAcceptedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageReadbackAcceptedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal MessageReadbackAcceptedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void NewLabMessageCompletedEventHandler(object sender, NewLabMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewLabMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal NewLabMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ResendLabMessageNotificationCompletedEventHandler(object sender, ResendLabMessageNotificationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResendLabMessageNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ResendLabMessageNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void LabMessageReadCompletedEventHandler(object sender, LabMessageReadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LabMessageReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LabMessageReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void LabMessageDeclinedCompletedEventHandler(object sender, LabMessageDeclinedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LabMessageDeclinedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LabMessageDeclinedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void LabMessageReadbackCompletedEventHandler(object sender, LabMessageReadbackCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LabMessageReadbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LabMessageReadbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void NewLabMessageReplyCompletedEventHandler(object sender, NewLabMessageReplyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewLabMessageReplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal NewLabMessageReplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void LabMessageReadbackFailureCompletedEventHandler(object sender, LabMessageReadbackFailureCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LabMessageReadbackFailureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal LabMessageReadbackFailureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void TEST_OutboundCallCompletedEventHandler(object sender, TEST_OutboundCallCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TEST_OutboundCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal TEST_OutboundCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void TEST_GetCallStatusCompletedEventHandler(object sender, TEST_GetCallStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TEST_GetCallStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal TEST_GetCallStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void NewDepartmentMessageCompletedEventHandler(object sender, NewDepartmentMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewDepartmentMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal NewDepartmentMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DepartmentMessageDeclinedCompletedEventHandler(object sender, DepartmentMessageDeclinedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepartmentMessageDeclinedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DepartmentMessageDeclinedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DepartmentMessageReadCompletedEventHandler(object sender, DepartmentMessageReadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepartmentMessageReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DepartmentMessageReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DepartmentMessageReadbackCompletedEventHandler(object sender, DepartmentMessageReadbackCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepartmentMessageReadbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DepartmentMessageReadbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DepartmentMessageReadbackAcceptedCompletedEventHandler(object sender, DepartmentMessageReadbackAcceptedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DepartmentMessageReadbackAcceptedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DepartmentMessageReadbackAcceptedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void NewDepartmentReplyCompletedEventHandler(object sender, NewDepartmentReplyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewDepartmentReplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal NewDepartmentReplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ResendDepartmentMessageNotificationCompletedEventHandler(object sender, ResendDepartmentMessageNotificationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResendDepartmentMessageNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ResendDepartmentMessageNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}
