//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 4/29/2009 7:59:19 PM
namespace northwndModel1
{
    
    /// <summary>
    /// There are no comments for northwndEntities5 in the schema.
    /// </summary>
    public partial class northwndEntities5 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new northwndEntities5 object using the connection string found in the 'northwndEntities5' section of the application configuration file.
        /// </summary>
        public northwndEntities5() : 
                base("name=northwndEntities5", "northwndEntities5")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new northwndEntities5 object.
        /// </summary>
        public northwndEntities5(string connectionString) : 
                base(connectionString, "northwndEntities5")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new northwndEntities5 object.
        /// </summary>
        public northwndEntities5(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "northwndEntities5")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for AccountTPT in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AccountTPT> AccountTPT
        {
            get
            {
                if ((this._AccountTPT == null))
                {
                    this._AccountTPT = base.CreateQuery<AccountTPT>("[AccountTPT]");
                }
                return this._AccountTPT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AccountTPT> _AccountTPT;
        /// <summary>
        /// There are no comments for LoanTPT in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LoanTPT> LoanTPT
        {
            get
            {
                if ((this._LoanTPT == null))
                {
                    this._LoanTPT = base.CreateQuery<LoanTPT>("[LoanTPT]");
                }
                return this._LoanTPT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LoanTPT> _LoanTPT;
        /// <summary>
        /// There are no comments for MortgageTPT in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MortgageTPT> MortgageTPT
        {
            get
            {
                if ((this._MortgageTPT == null))
                {
                    this._MortgageTPT = base.CreateQuery<MortgageTPT>("[MortgageTPT]");
                }
                return this._MortgageTPT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MortgageTPT> _MortgageTPT;
        /// <summary>
        /// There are no comments for AccountTPT in the schema.
        /// </summary>
        public void AddToAccountTPT(AccountTPT accountTPT)
        {
            base.AddObject("AccountTPT", accountTPT);
        }
        /// <summary>
        /// There are no comments for LoanTPT in the schema.
        /// </summary>
        public void AddToLoanTPT(LoanTPT loanTPT)
        {
            base.AddObject("LoanTPT", loanTPT);
        }
        /// <summary>
        /// There are no comments for MortgageTPT in the schema.
        /// </summary>
        public void AddToMortgageTPT(MortgageTPT mortgageTPT)
        {
            base.AddObject("MortgageTPT", mortgageTPT);
        }
    }
    /// <summary>
    /// There are no comments for northwndModel1.AccountTPT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AccountNumber
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="northwndModel1", Name="AccountTPT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AccountTPT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AccountTPT object.
        /// </summary>
        /// <param name="accountNumber">Initial value of AccountNumber.</param>
        public static AccountTPT CreateAccountTPT(int accountNumber)
        {
            AccountTPT accountTPT = new AccountTPT();
            accountTPT.AccountNumber = accountNumber;
            return accountTPT;
        }
        /// <summary>
        /// There are no comments for Property AccountNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountNumber
        {
            get
            {
                return this._AccountNumber;
            }
            set
            {
                this.OnAccountNumberChanging(value);
                this.ReportPropertyChanging("AccountNumber");
                this._AccountNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountNumber");
                this.OnAccountNumberChanged();
            }
        }
        private int _AccountNumber;
        partial void OnAccountNumberChanging(int value);
        partial void OnAccountNumberChanged();
        /// <summary>
        /// There are no comments for Property Balance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Balance
        {
            get
            {
                return this._Balance;
            }
            set
            {
                this.OnBalanceChanging(value);
                this.ReportPropertyChanging("Balance");
                this._Balance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Balance");
                this.OnBalanceChanged();
            }
        }
        private global::System.Nullable<int> _Balance;
        partial void OnBalanceChanging(global::System.Nullable<int> value);
        partial void OnBalanceChanged();
    }
    /// <summary>
    /// There are no comments for northwndModel1.LoanTPT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AccountNumber
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="northwndModel1", Name="LoanTPT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LoanTPT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LoanTPT object.
        /// </summary>
        /// <param name="accountNumber">Initial value of AccountNumber.</param>
        public static LoanTPT CreateLoanTPT(int accountNumber)
        {
            LoanTPT loanTPT = new LoanTPT();
            loanTPT.AccountNumber = accountNumber;
            return loanTPT;
        }
        /// <summary>
        /// There are no comments for Property AccountNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountNumber
        {
            get
            {
                return this._AccountNumber;
            }
            set
            {
                this.OnAccountNumberChanging(value);
                this.ReportPropertyChanging("AccountNumber");
                this._AccountNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountNumber");
                this.OnAccountNumberChanged();
            }
        }
        private int _AccountNumber;
        partial void OnAccountNumberChanging(int value);
        partial void OnAccountNumberChanged();
        /// <summary>
        /// There are no comments for Property Term in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Term
        {
            get
            {
                return this._Term;
            }
            set
            {
                this.OnTermChanging(value);
                this.ReportPropertyChanging("Term");
                this._Term = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Term");
                this.OnTermChanged();
            }
        }
        private global::System.Nullable<int> _Term;
        partial void OnTermChanging(global::System.Nullable<int> value);
        partial void OnTermChanged();
        /// <summary>
        /// There are no comments for Property Principal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Principal
        {
            get
            {
                return this._Principal;
            }
            set
            {
                this.OnPrincipalChanging(value);
                this.ReportPropertyChanging("Principal");
                this._Principal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Principal");
                this.OnPrincipalChanged();
            }
        }
        private global::System.Nullable<int> _Principal;
        partial void OnPrincipalChanging(global::System.Nullable<int> value);
        partial void OnPrincipalChanged();
    }
    /// <summary>
    /// There are no comments for northwndModel1.MortgageTPT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AccountNumber
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="northwndModel1", Name="MortgageTPT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MortgageTPT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MortgageTPT object.
        /// </summary>
        /// <param name="accountNumber">Initial value of AccountNumber.</param>
        public static MortgageTPT CreateMortgageTPT(int accountNumber)
        {
            MortgageTPT mortgageTPT = new MortgageTPT();
            mortgageTPT.AccountNumber = accountNumber;
            return mortgageTPT;
        }
        /// <summary>
        /// There are no comments for Property AccountNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountNumber
        {
            get
            {
                return this._AccountNumber;
            }
            set
            {
                this.OnAccountNumberChanging(value);
                this.ReportPropertyChanging("AccountNumber");
                this._AccountNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AccountNumber");
                this.OnAccountNumberChanged();
            }
        }
        private int _AccountNumber;
        partial void OnAccountNumberChanging(int value);
        partial void OnAccountNumberChanged();
        /// <summary>
        /// There are no comments for Property Tax in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Tax
        {
            get
            {
                return this._Tax;
            }
            set
            {
                this.OnTaxChanging(value);
                this.ReportPropertyChanging("Tax");
                this._Tax = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Tax");
                this.OnTaxChanged();
            }
        }
        private global::System.Nullable<int> _Tax;
        partial void OnTaxChanging(global::System.Nullable<int> value);
        partial void OnTaxChanged();
    }
}
