////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Arun.Manglick.SL3.BL", ClrNamespace = "arun.manglick.sl3.bl")]

//namespace arun.manglick.sl3.bl
//{
//    using System.Runtime.Serialization;


//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name = "Product", Namespace = "http://Arun.Manglick.SL3.BL")]
//    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
//    {

//        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

//        private string DescriptionField;

//        private string ModelNameField;

//        private string ModelNumberField;

//        private int ProductIdField;

//        private double UnitCostField;

//        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
//        {
//            get
//            {
//                return this.extensionDataField;
//            }
//            set
//            {
//                this.extensionDataField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Description
//        {
//            get
//            {
//                return this.DescriptionField;
//            }
//            set
//            {
//                this.DescriptionField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string ModelName
//        {
//            get
//            {
//                return this.ModelNameField;
//            }
//            set
//            {
//                this.ModelNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string ModelNumber
//        {
//            get
//            {
//                return this.ModelNumberField;
//            }
//            set
//            {
//                this.ModelNumberField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int ProductId
//        {
//            get
//            {
//                return this.ProductIdField;
//            }
//            set
//            {
//                this.ProductIdField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public double UnitCost
//        {
//            get
//            {
//                return this.UnitCostField;
//            }
//            set
//            {
//                this.UnitCostField = value;
//            }
//        }
//    }
//}


//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.ArunManglick.Silverlight3.com/ProductSvc", ConfigurationName = "IProductSvc")]
//public interface IProductSvc
//{

//    [System.ServiceModel.OperationContractAttribute(Action = "http://www.ArunManglick.Silverlight3.com/ProductSvc/IProductSvc/GetAllProducts", ReplyAction = "http://www.ArunManglick.Silverlight3.com/ProductSvc/IProductSvc/GetAllProductsRes" +
//        "ponse")]
//    arun.manglick.sl3.bl.Product[] GetAllProducts();

//    [System.ServiceModel.OperationContractAttribute(Action = "http://www.ArunManglick.Silverlight3.com/ProductSvc/IProductSvc/GetAllProducts", ReplyAction = "http://www.ArunManglick.Silverlight3.com/ProductSvc/IProductSvc/GetAllProductsRes" +
//        "ponse")]
//    System.Threading.Tasks.Task<arun.manglick.sl3.bl.Product[]> GetAllProductsAsync();
//}

//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//public interface IProductSvcChannel : IProductSvc, System.ServiceModel.IClientChannel
//{
//}

//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//public partial class ProductSvcClient : System.ServiceModel.ClientBase<IProductSvc>, IProductSvc
//{

//    public ProductSvcClient()
//    {
//    }

//    public ProductSvcClient(string endpointConfigurationName) :
//        base(endpointConfigurationName)
//    {
//    }

//    public ProductSvcClient(string endpointConfigurationName, string remoteAddress) :
//        base(endpointConfigurationName, remoteAddress)
//    {
//    }

//    public ProductSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
//        base(endpointConfigurationName, remoteAddress)
//    {
//    }

//    public ProductSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
//        base(binding, remoteAddress)
//    {
//    }

//    public arun.manglick.sl3.bl.Product[] GetAllProducts()
//    {
//        return base.Channel.GetAllProducts();
//    }

//    public System.Threading.Tasks.Task<arun.manglick.sl3.bl.Product[]> GetAllProductsAsync()
//    {
//        return base.Channel.GetAllProductsAsync();
//    }
//}
