//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloIndigoClient.HIServiceReferenceMC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkItem", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelloIndigoClient.HIServiceReferenceMC.MP3Link))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelloIndigoClient.HIServiceReferenceMC.GigInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelloIndigoClient.HIServiceReferenceMC.PhotoLink))]
    public partial class LinkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        private string TitleField;
        
        private string DescriptionField;
        
        private System.DateTime DateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HelloIndigoClient.HIServiceReferenceMC.LinkItemCategories CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateStart {
            get {
                return this.DateStartField;
            }
            set {
                if ((this.DateStartField.Equals(value) != true)) {
                    this.DateStartField = value;
                    this.RaisePropertyChanged("DateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime DateEnd {
            get {
                return this.DateEndField;
            }
            set {
                if ((this.DateEndField.Equals(value) != true)) {
                    this.DateEndField = value;
                    this.RaisePropertyChanged("DateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public HelloIndigoClient.HIServiceReferenceMC.LinkItemCategories Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MP3Link", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class MP3Link : HelloIndigoClient.HIServiceReferenceMC.LinkItem {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GigInfo", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class GigInfo : HelloIndigoClient.HIServiceReferenceMC.LinkItem {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoLink", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class PhotoLink : HelloIndigoClient.HIServiceReferenceMC.LinkItem {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkItemCategories", Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    public enum LinkItemCategories : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Event = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Music = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pics = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="HIServiceReferenceMC.IHelloIndigoService")]
    public interface IHelloIndigoService {
        
        // CODEGEN: Generating message contract since the operation SaveGig is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IHelloIndigoService/SaveGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IHelloIndigoService/SaveGigResponse" +
            "")]
        HelloIndigoClient.HIServiceReferenceMC.SaveGigResponse SaveGig(HelloIndigoClient.HIServiceReferenceMC.SaveGigRequest request);
        
        // CODEGEN: Generating message contract since the operation GetGig is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IHelloIndigoService/GetGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IHelloIndigoService/GetGigResponse")]
        HelloIndigoClient.HIServiceReferenceMC.GetGigResponse GetGig(HelloIndigoClient.HIServiceReferenceMC.GetGigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", Order=0)]
        public HelloIndigoClient.HIServiceReferenceMC.LinkItem Item;
        
        public SaveGigRequest() {
        }
        
        public SaveGigRequest(HelloIndigoClient.HIServiceReferenceMC.LinkItem Item) {
            this.Item = Item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGigResponse {
        
        public SaveGigResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGigRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06")]
        public string LicenseKey;
        
        public GetGigRequest() {
        }
        
        public GetGigRequest(string LicenseKey) {
            this.LicenseKey = LicenseKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", Order=0)]
        public HelloIndigoClient.HIServiceReferenceMC.LinkItem Item;
        
        public GetGigResponse() {
        }
        
        public GetGigResponse(HelloIndigoClient.HIServiceReferenceMC.LinkItem Item) {
            this.Item = Item;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IHelloIndigoServiceChannel : HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloIndigoServiceClient : System.ServiceModel.ClientBase<HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService>, HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService {
        
        public HelloIndigoServiceClient() {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloIndigoClient.HIServiceReferenceMC.SaveGigResponse HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService.SaveGig(HelloIndigoClient.HIServiceReferenceMC.SaveGigRequest request) {
            return base.Channel.SaveGig(request);
        }
        
        public void SaveGig(HelloIndigoClient.HIServiceReferenceMC.LinkItem Item) {
            HelloIndigoClient.HIServiceReferenceMC.SaveGigRequest inValue = new HelloIndigoClient.HIServiceReferenceMC.SaveGigRequest();
            inValue.Item = Item;
            HelloIndigoClient.HIServiceReferenceMC.SaveGigResponse retVal = ((HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService)(this)).SaveGig(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloIndigoClient.HIServiceReferenceMC.GetGigResponse HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService.GetGig(HelloIndigoClient.HIServiceReferenceMC.GetGigRequest request) {
            return base.Channel.GetGig(request);
        }
        
        public HelloIndigoClient.HIServiceReferenceMC.LinkItem GetGig(string LicenseKey) {
            HelloIndigoClient.HIServiceReferenceMC.GetGigRequest inValue = new HelloIndigoClient.HIServiceReferenceMC.GetGigRequest();
            inValue.LicenseKey = LicenseKey;
            HelloIndigoClient.HIServiceReferenceMC.GetGigResponse retVal = ((HelloIndigoClient.HIServiceReferenceMC.IHelloIndigoService)(this)).GetGig(inValue);
            return retVal.Item;
        }
    }
}
